/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FixesRouteImport } from './routes/fixes'
import { Route as FailuresRouteImport } from './routes/failures'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditAuditIdRouteImport } from './routes/audit.$auditId'

const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FixesRoute = FixesRouteImport.update({
  id: '/fixes',
  path: '/fixes',
  getParentRoute: () => rootRouteImport,
} as any)
const FailuresRoute = FailuresRouteImport.update({
  id: '/failures',
  path: '/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditAuditIdRoute = AuditAuditIdRouteImport.update({
  id: '/$auditId',
  path: '/$auditId',
  getParentRoute: () => AuditRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/failures': typeof FailuresRoute
  '/fixes': typeof FixesRoute
  '/history': typeof HistoryRoute
  '/plan': typeof PlanRoute
  '/audit/$auditId': typeof AuditAuditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/failures': typeof FailuresRoute
  '/fixes': typeof FixesRoute
  '/history': typeof HistoryRoute
  '/plan': typeof PlanRoute
  '/audit/$auditId': typeof AuditAuditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/failures': typeof FailuresRoute
  '/fixes': typeof FixesRoute
  '/history': typeof HistoryRoute
  '/plan': typeof PlanRoute
  '/audit/$auditId': typeof AuditAuditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/failures'
    | '/fixes'
    | '/history'
    | '/plan'
    | '/audit/$auditId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/failures'
    | '/fixes'
    | '/history'
    | '/plan'
    | '/audit/$auditId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/dashboard'
    | '/failures'
    | '/fixes'
    | '/history'
    | '/plan'
    | '/audit/$auditId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FailuresRoute: typeof FailuresRoute
  FixesRoute: typeof FixesRoute
  HistoryRoute: typeof HistoryRoute
  PlanRoute: typeof PlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixes': {
      id: '/fixes'
      path: '/fixes'
      fullPath: '/fixes'
      preLoaderRoute: typeof FixesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failures': {
      id: '/failures'
      path: '/failures'
      fullPath: '/failures'
      preLoaderRoute: typeof FailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/$auditId': {
      id: '/audit/$auditId'
      path: '/$auditId'
      fullPath: '/audit/$auditId'
      preLoaderRoute: typeof AuditAuditIdRouteImport
      parentRoute: typeof AuditRoute
    }
  }
}

interface AuditRouteChildren {
  AuditAuditIdRoute: typeof AuditAuditIdRoute
}

const AuditRouteChildren: AuditRouteChildren = {
  AuditAuditIdRoute: AuditAuditIdRoute,
}

const AuditRouteWithChildren = AuditRoute._addFileChildren(AuditRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FailuresRoute: FailuresRoute,
  FixesRoute: FixesRoute,
  HistoryRoute: HistoryRoute,
  PlanRoute: PlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
